[04/Jun/2014 21:03:17] DEBUG [sgtioapp.views:9] User searched forleg
[04/Jun/2014 21:03:18] INFO [requests.packages.urllib3.connectionpool:657] Starting new HTTPS connection (1): api.sgt.io
[04/Jun/2014 21:03:25] DEBUG [requests.packages.urllib3.connectionpool:350] "GET /products/?api_key=4c4ec8961617eee94e2469b1fea9f5587d64b6d3&q=leg&format=json HTTP/1.1" 200 None
[04/Jun/2014 21:03:34] DEBUG [sgtioapp.views:9] User searched forhead
[04/Jun/2014 21:03:34] INFO [requests.packages.urllib3.connectionpool:657] Starting new HTTPS connection (1): api.sgt.io
[04/Jun/2014 21:03:39] DEBUG [requests.packages.urllib3.connectionpool:350] "GET /products/?api_key=4c4ec8961617eee94e2469b1fea9f5587d64b6d3&q=head&format=json HTTP/1.1" 200 None
[04/Jun/2014 21:06:05] DEBUG [sgtioapp.views:9] User searched for tail
[04/Jun/2014 21:06:05] INFO [requests.packages.urllib3.connectionpool:657] Starting new HTTPS connection (1): api.sgt.io
[04/Jun/2014 21:06:10] DEBUG [requests.packages.urllib3.connectionpool:350] "GET /products/?api_key=4c4ec8961617eee94e2469b1fea9f5587d64b6d3&q=tail&format=json HTTP/1.1" 200 None
[05/Jun/2014 13:16:06] WARNING [django.request:143] Not Found: /
[05/Jun/2014 13:16:06] WARNING [django.request:143] Not Found: /
[05/Jun/2014 13:29:15] ERROR [django.request:224] Internal Server Error: /sgtioapp/
Traceback (most recent call last):
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jasonli/IntroProject/sgtioapp/views.py", line 9, in sgtio_template
    logger.debug("User searched for " + product)
TypeError: cannot concatenate 'str' and 'NoneType' objects
[05/Jun/2014 13:29:15] WARNING [django.request:143] Not Found: /favicon.ico
[05/Jun/2014 13:32:29] ERROR [django.request:224] Internal Server Error: /sgtioapp/
Traceback (most recent call last):
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jasonli/IntroProject/sgtioapp/views.py", line 11, in sgtio_template
    url = "https://api.sgt.io/products/?api_key=4c4ec8961617eee94e2469b1fea9f5587d64b6d3&q=" + product + "&format=json"
TypeError: cannot concatenate 'str' and 'NoneType' objects
[05/Jun/2014 13:32:36] ERROR [django.request:224] Internal Server Error: /sgtioapp/
Traceback (most recent call last):
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jasonli/IntroProject/sgtioapp/views.py", line 11, in sgtio_template
    url = "https://api.sgt.io/products/?api_key=4c4ec8961617eee94e2469b1fea9f5587d64b6d3&q=" + product + "&format=json"
TypeError: cannot concatenate 'str' and 'NoneType' objects
[05/Jun/2014 13:35:34] ERROR [django.request:224] Internal Server Error: /sgtioapp/
Traceback (most recent call last):
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jasonli/IntroProject/sgtioapp/views.py", line 10, in sgtio_template
    if products is not None:
UnboundLocalError: local variable 'products' referenced before assignment
[05/Jun/2014 13:38:54] ERROR [django.request:224] Internal Server Error: /sgtioapp/
Traceback (most recent call last):
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jasonli/IntroProject/sgtioapp/views.py", line 13, in sgtio_template
    url = "https://api.sgt.io/products/?api_key=4c4ec8961617eee94e2469b1fea9f5587d64b6d3&q=" + product + "&format=json"
TypeError: cannot concatenate 'str' and 'NoneType' objects
[05/Jun/2014 13:39:49] ERROR [django.request:224] Internal Server Error: /sgtioapp/
Traceback (most recent call last):
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jasonli/IntroProject/sgtioapp/views.py", line 14, in sgtio_template
    r = requests.get(url)
UnboundLocalError: local variable 'url' referenced before assignment
[05/Jun/2014 13:40:26] ERROR [django.request:224] Internal Server Error: /sgtioapp/
Traceback (most recent call last):
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 130, in get_response
    raise ValueError("The view %s.%s didn't return an HttpResponse object." % (callback.__module__, view_name))
ValueError: The view sgtioapp.views.sgtio_template didn't return an HttpResponse object.
[05/Jun/2014 13:49:22] ERROR [django.request:224] Internal Server Error: /sgtioapp/
Traceback (most recent call last):
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jasonli/IntroProject/sgtioapp/views.py", line 17, in sgtio_template
    return render_to_response('template.html')
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/template/loader.py", line 164, in render_to_string
    return t.render(Context(dictionary))
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/template/debug.py", line 88, in render
    output = self.filter_expression.resolve(context)
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/template/base.py", line 607, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/template/base.py", line 735, in resolve
    value = self._resolve_lookup(context)
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/template/base.py", line 781, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [layout] in u"[{'False': False, 'None': None, 'True': True}, {}]"
[05/Jun/2014 13:54:33] ERROR [django.request:224] Internal Server Error: /sgtioapp/
Traceback (most recent call last):
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jasonli/IntroProject/sgtioapp/views.py", line 17, in sgtio_template
    return render_to_response('template.html')
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/template/loader.py", line 164, in render_to_string
    return t.render(Context(dictionary))
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/template/debug.py", line 88, in render
    output = self.filter_expression.resolve(context)
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/template/base.py", line 607, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/template/base.py", line 735, in resolve
    value = self._resolve_lookup(context)
  File "/home/jasonli/Envs/introproject/local/lib/python2.7/site-packages/django/template/base.py", line 781, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [layout] in u"[{'False': False, 'None': None, 'True': True}, {}]"
[05/Jun/2014 13:55:02] DEBUG [sgtioapp.views:11] User searched for 
[05/Jun/2014 13:55:02] INFO [requests.packages.urllib3.connectionpool:657] Starting new HTTPS connection (1): api.sgt.io
[05/Jun/2014 13:55:02] DEBUG [requests.packages.urllib3.connectionpool:350] "GET /products/?api_key=4c4ec8961617eee94e2469b1fea9f5587d64b6d3&q=&format=json HTTP/1.1" 200 None
[05/Jun/2014 13:55:11] DEBUG [sgtioapp.views:11] User searched for walmart
[05/Jun/2014 13:55:11] INFO [requests.packages.urllib3.connectionpool:657] Starting new HTTPS connection (1): api.sgt.io
[05/Jun/2014 13:55:11] DEBUG [requests.packages.urllib3.connectionpool:350] "GET /products/?api_key=4c4ec8961617eee94e2469b1fea9f5587d64b6d3&q=walmart&format=json HTTP/1.1" 200 None
[05/Jun/2014 13:55:22] DEBUG [sgtioapp.views:11] User searched for food
[05/Jun/2014 13:55:22] INFO [requests.packages.urllib3.connectionpool:657] Starting new HTTPS connection (1): api.sgt.io
[05/Jun/2014 13:55:27] DEBUG [requests.packages.urllib3.connectionpool:350] "GET /products/?api_key=4c4ec8961617eee94e2469b1fea9f5587d64b6d3&q=food&format=json HTTP/1.1" 200 None
